test: add test.sh

diff --git a/bin/stern b/bin/stern
--- a/bin/stern
+++ b/bin/stern
@@ -28,10 +28,10 @@ Unzip() {
   local target_file_path="${3:?}"
   if [[ "${source_zip_path:?}" =~ .+\.(tar|tgz|tar\.gz)$ ]]; then
     local file_in_archive && file_in_archive=$(tar tvf "${source_zip_path:?}" | awk -F" " "/[\/ ]${filename_in_archive:?}$/ {print \$NF}")
-    RecExec bash -c "tar -O -xf \"${source_zip_path:?}\" \"${file_in_archive:?}\" > \"${target_file_path:?}\""
+    LogshExec bash -c "tar -O -xf \"${source_zip_path:?}\" \"${file_in_archive:?}\" > \"${target_file_path:?}\""
   elif [[ "${source_zip_path:?}" =~ .+\.zip$ ]]; then
     local file_in_archive && file_in_archive=$(unzip -l "${source_zip_path:?}" | awk -F" " "/[\/ ]${filename_in_archive:?}$/ {print \$NF}")
-    RecExec bash -c "unzip -p -o \"${source_zip_path:?}\" \"${file_in_archive:?}\" > \"${target_file_path:?}\""
+    LogshExec bash -c "unzip -p -o \"${source_zip_path:?}\" \"${file_in_archive:?}\" > \"${target_file_path:?}\""
   fi
 }
 
@@ -48,20 +48,20 @@ InstallProgram() {
   elif [[ ${machine_arch:?} = arm64 ]]; then
     prog_arch=arm64
   else
-    RecCritical "arch (${machine_arch:?}) is not supported"
+    LogshError "arch (${machine_arch:?}) is not supported"
     exit 1
   fi
   local download_url && download_url="$(FindTargetZipDownloadURL "${prog_version:?}" "${prog_os:?}" "${prog_arch:?}")"
   local downloaded_path && downloaded_path=${prog_version_tmp_dir:?}/$(basename "${download_url:?}")
   # download
-  RecNotice "Download ${download_url:?}"
+  LogshNotice "Download ${download_url:?}"
   DownloadURL "${download_url:?}" "${downloaded_path:?}"
   # install
-  RecNotice "Install ${downloaded_path:?} to ${prog_version_exe:?}"
+  LogshNotice "Install ${downloaded_path:?} to ${prog_version_exe:?}"
   local unziped_path="${prog_version_tmp_dir:?}/${exe_filename:?}"
   Unzip "${downloaded_path:?}" "${exe_filename:?}" "${unziped_path:?}"
-  RecExec mv -f "${unziped_path:?}" "${prog_version_exe:?}"
-  RecExec chmod +x "${prog_version_exe:?}"
+  LogshExec mv -f "${unziped_path:?}" "${prog_version_exe:?}"
+  LogshExec chmod +x "${prog_version_exe:?}"
 }
 
 ExecProgram() {
@@ -74,41 +74,42 @@ ExecProgram() {
   if echo "$*" | grep -q -- "--context[[:space:]=]"; then
     exec "${prog_version_exe:?}" "$@" <&0
   elif [[ ${KUBECTL_CONTEXT:-} ]]; then
-    RecInfo "$ ${exe_filename:?} --context=${KUBECTL_CONTEXT:?} $*"
+    LogshInfo "$ ${exe_filename:?} --context=${KUBECTL_CONTEXT:?} $*"
     exec "${prog_version_exe:?}" --context="${KUBECTL_CONTEXT:?}" "$@" <&0
   else
     exec "${prog_version_exe:?}" "$@" <&0
   fi
 }
 
-# LISENCE: https://github.com/kunitsucom/rec.sh/blob/HEAD/LICENSE
+# LISENCE: https://github.com/kunitsucom/log.sh/blob/HEAD/LICENSE
 # Common
-if [ -t 2 ]; then REC_COLOR=true; else REC_COLOR=''; fi
-_recRFC3339() { date "+%Y-%m-%dT%H:%M:%S%z" | sed "s/\(..\)$/:\1/"; }
-_recCmd() { for a in "$@"; do if echo "${a:-}" | grep -Eq "[[:blank:]]"; then printf "'%s' " "${a:-}"; else printf "%s " "${a:-}"; fi; done | sed "s/ $//"; }
+if [ "${LOGSH_COLOR:-}" ] || [ -t 2 ] ; then LOGSH_COLOR=true; else LOGSH_COLOR=''; fi
+_logshRFC3339() { date "+%Y-%m-%dT%H:%M:%S%z" | sed "s/\(..\)$/:\1/"; }
+_logshCmd() { for a in "$@"; do if echo "${a:-}" | grep -Eq "[[:blank:]]"; then printf "'%s' " "${a:-}"; else printf "%s " "${a:-}"; fi; done | sed "s/ $//"; }
 # Color
-RecDefault() { test "  ${REC_SEVERITY:-0}" -gt 000 2>/dev/null || echo "$*" | awk "{print   \"$(_recRFC3339) [${REC_COLOR:+\\033[0;35m}  DEFAULT${REC_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
-RecDebug() { test "    ${REC_SEVERITY:-0}" -gt 100 2>/dev/null || echo "$*" | awk "{print   \"$(_recRFC3339) [${REC_COLOR:+\\033[0;34m}    DEBUG${REC_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
-RecInfo() { test "     ${REC_SEVERITY:-0}" -gt 200 2>/dev/null || echo "$*" | awk "{print   \"$(_recRFC3339) [${REC_COLOR:+\\033[0;32m}     INFO${REC_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
-RecNotice() { test "   ${REC_SEVERITY:-0}" -gt 300 2>/dev/null || echo "$*" | awk "{print   \"$(_recRFC3339) [${REC_COLOR:+\\033[0;36m}   NOTICE${REC_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
-RecWarning() { test "  ${REC_SEVERITY:-0}" -gt 400 2>/dev/null || echo "$*" | awk "{print   \"$(_recRFC3339) [${REC_COLOR:+\\033[0;33m}  WARNING${REC_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
-RecError() { test "    ${REC_SEVERITY:-0}" -gt 500 2>/dev/null || echo "$*" | awk "{print   \"$(_recRFC3339) [${REC_COLOR:+\\033[0;31m}    ERROR${REC_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
-RecCritical() { test " ${REC_SEVERITY:-0}" -gt 600 2>/dev/null || echo "$*" | awk "{print \"$(_recRFC3339) [${REC_COLOR:+\\033[0;1;31m} CRITICAL${REC_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
-RecAlert() { test "    ${REC_SEVERITY:-0}" -gt 700 2>/dev/null || echo "$*" | awk "{print   \"$(_recRFC3339) [${REC_COLOR:+\\033[0;41m}    ALERT${REC_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
-RecEmergency() { test "${REC_SEVERITY:-0}" -gt 800 2>/dev/null || echo "$*" | awk "{print \"$(_recRFC3339) [${REC_COLOR:+\\033[0;1;41m}EMERGENCY${REC_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
-RecExec() { RecInfo "$ $(_recCmd "$@")" && "$@"; }
-RecRun() { _dlm="####R#E#C#D#E#L#I#M#I#T#E#R####" && _all=$({ _out=$("$@") && _rtn=$? || _rtn=$? && printf "\n%s" "${_dlm:?}${_out:-}" && return "${_rtn:-0}"; } 2>&1) && _rtn=$? || _rtn=$? && _dlmno=$(echo "${_all:-}" | sed -n "/${_dlm:?}/=") && _cmd=$(_recCmd "$@") && _stdout=$(echo "${_all:-}" | tail -n +"${_dlmno:-1}" | sed "s/^${_dlm:?}//") && _stderr=$(echo "${_all:-}" | head -n "${_dlmno:-1}" | grep -v "^${_dlm:?}") && RecInfo "$ ${_cmd:-}" && { [ -z "${_stdout:-}" ] || RecInfo "${_stdout:?}"; } && { [ -z "${_stderr:-}" ] || RecWarning "${_stderr:?}"; } && return "${_rtn:-0}"; }
+LogshDefault() { test "  ${LOGSH_LEVEL:-0}" -gt 000 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;35m}  DEFAULT${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
+LogshDebug() { test "    ${LOGSH_LEVEL:-0}" -gt 100 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;34m}    DEBUG${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
+LogshInfo() { test "     ${LOGSH_LEVEL:-0}" -gt 200 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;32m}     INFO${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
+LogshNotice() { test "   ${LOGSH_LEVEL:-0}" -gt 300 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;36m}   NOTICE${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
+LogshWarn() { test "     ${LOGSH_LEVEL:-0}" -gt 400 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;33m}     WARN${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
+LogshWarning() { test "  ${LOGSH_LEVEL:-0}" -gt 400 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;33m}  WARNING${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
+LogshError() { test "    ${LOGSH_LEVEL:-0}" -gt 500 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;31m}    ERROR${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
+LogshCritical() { test " ${LOGSH_LEVEL:-0}" -gt 600 || echo "$*" | awk "{print \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;1;31m} CRITICAL${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
+LogshAlert() { test "    ${LOGSH_LEVEL:-0}" -gt 700 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;41m}    ALERT${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
+LogshEmergency() { test "${LOGSH_LEVEL:-0}" -gt 800 || echo "$*" | awk "{print \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;1;41m}EMERGENCY${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
+LogshExec() { LogshInfo "$ $(_logshCmd "$@")" && "$@"; }
+LogshRun() { _dlm="####R#E#C#D#E#L#I#M#I#T#E#R####" && _all=$({ _out=$("$@") && _rtn=$? || _rtn=$? && printf "\n%s" "${_dlm:?}${_out:-}" && return "${_rtn:-0}"; } 2>&1) && _rtn=$? || _rtn=$? && _dlmno=$(echo "${_all:-}" | sed -n "/${_dlm:?}/=") && _cmd=$(_logshCmd "$@") && _stdout=$(echo "${_all:-}" | tail -n +"${_dlmno:-1}" | sed "s/^${_dlm:?}//") && _stderr=$(echo "${_all:-}" | head -n "${_dlmno:-1}" | grep -v "^${_dlm:?}") && LogshInfo "$ ${_cmd:-}" && LogshInfo "${_stdout:-}" && { [ -z "${_stderr:-}" ] || LogshWarning "${_stderr:?}"; } && return "${_rtn:-0}"; }
 
 # versenv common
 DownloadURL() {
   local url="${1:?}"
   local file="${2:?}"
   if command -v curl >/dev/null; then
-    RecExec curl --tlsv1.2 --connect-timeout 2 --progress-bar -fLR "${url:?}" -o "${file:?}"
+    LogshExec curl --tlsv1.2 --connect-timeout 2 --progress-bar -fLR "${url:?}" -o "${file:?}"
   elif command -v wget >/dev/null; then
-    RecExec wget --secure-protocol=TLSv1_2 --dns-timeout=2 --connect-timeout=2 -q "${url:?}" -O "${file:?}"
+    LogshExec wget --secure-protocol=TLSv1_2 --dns-timeout=2 --connect-timeout=2 -q "${url:?}" -O "${file:?}"
   else
-    RecCritical "command not found: curl or wget"
+    LogshError "command not found: curl or wget"
     exit 127
   fi
 }
@@ -121,7 +122,7 @@ GetURLs() {
     elif command -v curl >/dev/null; then
       curl --tlsv1.2 --connect-timeout 2 -fLRSs "${url:?}"
     else
-      RecCritical "command not found: curl or wget"
+      LogshError "command not found: curl or wget"
       exit 127
     fi
   done
@@ -134,7 +135,7 @@ HeadURL() {
   elif command -v curl >/dev/null; then
     curl --tlsv1.2 --connect-timeout 2 -fIRSs "${url:?}"
   else
-    RecCritical "command not found: curl or wget"
+    LogshError "command not found: curl or wget"
     exit 127
   fi
 }
@@ -145,16 +146,16 @@ SubcommandSelfUpdate() {
   local tmp_dir=/tmp/versenv/bin
   local tmp_file=${tmp_dir:?}/${exe_filename:?}
   local backup_file="${tmp_file:?}.backup"
-  RecNotice "Download ${self_update_url:?}"
+  LogshNotice "Download ${self_update_url:?}"
   mkdir -p "${tmp_dir:?}"
   DownloadURL "${self_update_url:?}" "${tmp_file:?}"
-  RecNotice "Take backup ${script_file_path:?} to ${backup_file:?}"
-  RecExec mv -f "${script_file_path:?}" "${backup_file:?}"
-  RecNotice "Show the changes between old and new"
-  RecExec diff -u "${backup_file:?}" "${tmp_file:?}" || true
-  RecNotice "Update ${script_file_path:?} to ${self_update_url:?}"
-  RecExec chmod +x "${tmp_file:?}"
-  RecExec mv -f "${tmp_file:?}" "${script_file_path:?}"
+  LogshNotice "Take backup ${script_file_path:?} to ${backup_file:?}"
+  LogshExec mv -f "${script_file_path:?}" "${backup_file:?}"
+  LogshNotice "Show the changes between old and new"
+  LogshExec diff -u "${backup_file:?}" "${tmp_file:?}" || true
+  LogshNotice "Update ${script_file_path:?} to ${self_update_url:?}"
+  LogshExec chmod +x "${tmp_file:?}"
+  LogshExec mv -f "${tmp_file:?}" "${script_file_path:?}"
 }
 
 MustFoundCommands() {
@@ -169,7 +170,7 @@ MustFoundCommands() {
   if [[ "${#not_found_commands[@]}" -eq 0 ]]; then
     return
   fi
-  RecCritical "command not found: ${not_found_commands[*]}"
+  LogshError "command not found: ${not_found_commands[*]}"
   exit 127
 }
 
@@ -181,7 +182,7 @@ ResolveProgramVersion() {
       echo "${!env_key_version:?}"
     else
       ver=$(GetProgramLatestStableVersion)
-      RecNotice "env ${env_key_version:?} is not set. Use latest stable version: ${env_key_version:?}=${ver:-"?"}"
+      LogshNotice "env ${env_key_version:?} is not set. Use latest stable version: ${env_key_version:?}=${ver:-"?"}"
       echo "${ver:-}"
     fi
   )
@@ -189,7 +190,7 @@ ResolveProgramVersion() {
     echo "${version:?}"
     return 0
   else
-    RecCritical "Failed to resolve version"
+    LogshError "Failed to resolve version"
     return 1
   fi
 }
